fix(java): use Maven mirror, remove unnecessary plugins, other CI-stability improvements (#2253)
Contributes to https://github.com/rapidsai/cuvs-lucene/issues/145

Java builds have been failing like this:

```text
Error:  Unresolveable build extension: Plugin org.sonatype.plugins:nexus-staging-maven-plugin:1.6.7 or one of its dependencies could not be resolved:
	Failed to read artifact descriptor for org.sonatype.plugins:nexus-staging-maven-plugin:jar:1.6.7
```

This is hiding the true issue ... **we're getting rate-limited by Maven Central**, with requests hitting `429 (Too Many Requests)`.

This proposes the following changes to fix that:

* switching to the unofficial Maven Central read-only mirror on GCS
* removing unnecessary dependencies from `pom.xml`
* configuring Maven to download more slowly and wait longer between retries
* fine-tuning `changed-files` rules to reduce how often Java CI runs on PRs

And these other changes relevant to the Java builds:

* validating XML in `pre-commit` hooks (this did catch a syntax error in the Java examples' `pom.xml`!)
* removing unnecessary configuration for snapshots (this project doesn't publish or download snapshots)
* reformatting Java READMEs per https://yihui.org/en/2021/06/markdown-breath/

See inline comments for more details.

## Notes for Reviewers

### Impact

I don't believe there are any breaking changes in this PR. Our existing publishing process for `cuvs-java` should be unaffected and CI should become faster and more reliable.

If anything breaks because of it, assume that was unintentional.

### AI use

I'm not very familiar with Java packaging, so heavily relied on back-and-forth with an agent for help with this.

I wrote this PR description, code comments, and all inline review comments here myself.

My motivation is to unblock CI here and in `cuvs-lucene`. If a more qualified reviewer wants to close this and implement a different fix, please do.

Authors:
  - James Lamb (https://github.com/jameslamb)

Approvers:
  - Bradley Dice (https://github.com/bdice)
  - Corey J. Nolet (https://github.com/cjnolet)
  - Tim Liu (https://github.com/NvTimLiu)

URL: https://github.com/rapidsai/cuvs/pull/2253