Fix C compile error in `tiered_index.h` (#996)
This commit rephrases the definition of the `cuvsTieredIndexANNAlgo` enum in `tiered_index.h` to use a `typedef`.

With the old definition `enum cuvsTieredIndexANNAlgo{}`, compiling a C translation unit yields errors where `cuvsTieredIndexANNAlgo` is used without `enum`. (For instance at line#55 and line#88 of `tiered_index.h`.)
```
tiered_index.h:53:3: error: must use 'enum' tag to refer to type 'cuvsTieredIndexANNAlgo'
tiered_index.h:88:3: error: must use 'enum' tag to refer to type 'cuvsTieredIndexANNAlgo'
```

The typedef sorts this error out.

Authors:
  - MithunR (https://github.com/mythrocks)
  - Corey J. Nolet (https://github.com/cjnolet)

Approvers:
  - Corey J. Nolet (https://github.com/cjnolet)
  - Ben Frederickson (https://github.com/benfred)

URL: https://github.com/rapidsai/cuvs/pull/996